### ISSUE TITLE
IPython.core.display does not work

### ISSUE THREAD

**Issue by superlopuh** [jupyterlite/jupyterlite#1056]
## Description

Here's a cell that works in a local Jupyter notebook, and that I would've expected to work in Jupyterlite:

``` python
from IPython.core.display import Javascript
js_fib = """\
element.text(42)
"""
display(Javascript(js_fib))
```

This is the error I get: `Javascript Error: element.text is not a function`. 

I did some searching on the JupyterLite docs and could not find anything relevant. Is there a call I could replace it with to get it to display the result of the js computation?

## Expected behavior

I would expect either no error or a link to the page in the documentation about the IPython.core JS support.

## Context

- JupyterLite version: 0.1.0-beta.17
- Operating System and version: MacOS 12.6
- Browser and version: Firefox 111.0.1

**Comment by superlopuh** [comment]
Here's the link to the IPython docs:

https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Javascript

```
Create a Javascript display object given raw data.

When this object is returned by an expression or passed to the display function, it will result in the data being displayed in the frontend. If the data is a URL, the data will first be downloaded and then displayed.

In the Notebook, the containing element will be available as element, and jQuery will be available. Content appended to element will be visible in the output area.
```

I was hoping that this sort of thing would work in Jupyterlite also, although of course it might not be using jquery at all. Maybe there's some other way to display the information?

**Comment by martinRenou** [comment]
I see, thanks for the link.

So I guess this is more broadly a JupyterLab regression from Jupyter Notebook, it does not only concern JupyterLite. Note that Jupyter Notebook version 7 may remove this feature as well (cc. @jtpio who may know?).

**Comment by bollwyvl** [comment]
> `element.text(42)`

Yeah, one can forget about `jQuery`: the fact that we're not seeing `element is undefined` means you _have_ a handle, as per the [evaluation context](https://github.com/jupyterlab/jupyterlab/blob/master/packages/javascript-extension/src/index.ts#L14) in the JupyterLab upstream. Instead of... some version of jQuery, you have access to everything that DOM `div` can do, so something like this works fine, using just standards:

```py
Javascript("""
element.textContent = 42
""")
```

By _design_, in the Jupyter architecture, the kernel shouldn't know _anything_ about the client, a notebook document, or whatever. Things like "a reference in a particular third-party package to a particular DOM element" is a very leaky abstraction, then, and should likely be removed from the upstream documentation, even if JupyterLab has _partially_ maintained compatibility.

In the near term, one could publish an labextension, e.g. `@not-me/jupyterlab-good-ol-jquery`, that restored this behavior by replacing the plugin, but this would result in less-portable documents, as the trend will _certainly_ be for the security posture to continue to be tightened.

Looking forward, only _last month_ did all modern browsers get a way to _actually_ solve the underlying JS dependency problem, in the general case, with Safari 16.4 adding [scoped import maps](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) and [adopted stylesheets](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets). 

In the future, these standards will need to integrated into the mechanism for arbitrary JS code execution, and likely inside suitably-sandboxed `iframe` elements, and _ideally_ on a seperate port/domain. The web hacker in me cries, a bit, of course, but the Jupyter maintainers have had to look at the big picture, and do what we can to meet the needs not only of end user agency, but also accessibility, security, composability, and maintainability.

**Comment by superlopuh** [comment]
Thank you for the very informative comment! The logic makes sense to me, and since simple text output is all I need it solves my issue.
