### ISSUE TITLE
adapt jupyterlab extension to jupyterlite

### ISSUE THREAD

**Issue by djangoliv** [jupyterlite/jupyterlite#1091]
I have a jupyterlab extension (in React) that I would like to make compatible with jupyterlite. 
Some features are not useful in jupyterlite.
How can I do to know if I am in jupyterlite or in jupyterlab ?

```
# javascript (react)
if (<not in jupyterlite>) {
     // specific jupyterlab code
}

```

Regards

**Comment by djangoliv** [comment]
thanks @jtpio 
My extension is a collection of tools for training (like nbgrader https://github.com/jupyter/nbgrader).
For example, I have a button that saves student progress to a sqlite database, maybe I'll use redis later for that, but I want to disable that feature for now in jupyterlite.
If there's no other solution, I'll isolate the features, it's a lot of work, but it's a good idea.

**Comment by jtpio** [comment]
> If there's no other solution, I'll isolate the features, it's a lot of work, but it's a good idea.

Yes creating several plugins within an extension when the extension provides several functionalities is a good practice, because it will allow end users and deployers to choose which plugins they would like to disable if needed.

As a follow-up to this issue, maybe there could be a small section in the JupyterLite documentation to give directions for making JupyterLab extensions work in JupyterLite. For example on this page: https://jupyterlite.readthedocs.io/en/latest/howto/extensions/frontend.html.
