### ISSUE TITLE
Inconsistent loading of external files

### ISSUE THREAD

**Issue by sean-morris** [jupyterlite/jupyterlite#1107]
## Description

Sometimes I load JL and it "mounts" the drives or however we talk about here(!) and sees the file system. Other times it seems to not see the file system.  I have two instances where this occurs -- importing of a utility file as well as the loading of a local csv file.

You can see the situation [here](https://sean-morris.github.io/materials-sp22-jupyterlite/lab/index.html). If you navigate to hw/hw02/hw02.ipynb, there are two lines to notice:
- import d8error --> this is local python file used to make the stacktraces look nicer
- Table.read_table("president_births.csv").column('Birth Year')

I loaded the JL instance once and both lines returned a FileNotFound type error. I re-loaded the JL and then both lines worked.

## Expected behavior

The files load anytime the JL is brought up.

## Context

- JupyterLite version: 0.1.0
- Operating System and version: Mac OSX 10.15.7
- Browser and version: Chrome Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by jtpio** [comment]
Thanks @sean-morris for reporting.

This is likely an issue with the underlying `Service Worker` used for syncing files with the Python kernel.

Out of curiosity, would you be able to try unregister the service worker via the browser dev tools, and reload the page?

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/0be203cb-f7e6-428e-94c3-734346461581)

To see if the issue comes back afterwards.

**Comment by sean-morris** [comment]
Thanks @jtpio I should have come back here. It was definitely the Service Worker and more importantly, it was that I had forgotten that in order to register a ServiceWorker you need to be using TLS/SSL via https.
