### ISSUE TITLE
REPL app storage 

### ISSUE THREAD

**Issue by namfal** [jupyterlite/jupyterlite#1157]
### Problem

I am working with a Jupyterlite REPL application. I want to be able to save the contents so that when the user refreshes, it is not lost.  With regular JupyterLite instance (so not an iframe REPL), things are saved in the IndexedDB but so that's not an issue. 

I can't figure out how to do this in the documentation or if it is possible. Alternatively, I would like to know if it is possible to start the REPL application with a default notebook. I see that I can execute code on start using the url params, but is starting a notebook possible?

**Comment by jtpio** [comment]
@namfal the REPL application is meant to be disposable and is not backed by a notebook or file (it's based on the JupyterLab code console).

Maybe the notebook application would be a good option otherwise? https://jupyterlite.readthedocs.io/en/stable/_static/retro/notebooks/index.html?path=intro-retro.ipynb

**Comment by namfal** [comment]
Yes, I think that's exactly what I needed!  Thank you.
