### ISSUE TITLE
Unpin `myst-nb<1`

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#1257]
### Problem

https://github.com/jupyterlite/jupyterlite/pull/1256 pinned `myst-nb<1` on CI and ReadTheDocs to fix the recent build failures.

However we should remove that pin eventually.

### Suggested Improvement

Figure out what needs to be done to be able to remove the pin.

Might depend on https://github.com/executablebooks/MyST-NB/issues/572 to have an overview of the changes in `1.0`.

**Comment by agoose77** [comment]
I've tried to hunt down the build failure (which is caused by some MyST warnings triggering errors), but to no avail — I'm struggling to build the docs locally, which fails at step `docs:post:images`. I suspect the changes to references in `myst-parser>=1.0.0` are the cause, so it should be an easy fix if the references are indeed broken.

**Comment by jtpio** [comment]
> which fails at step `docs:post:images`

Arf I have seen it failing as well on Gitpod.

Maybe there is a way to work around that by running a `doit docs:sphinx` directly like on CI: https://github.com/jupyterlite/jupyterlite/blob/c12212cd1178a09c79b52de9b2fb962875c07e5b/.github/workflows/build.yml#L238C17-L238C30

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlite/jupyterlite/pull/1270, thanks @agoose77!
