### ISSUE TITLE
Fix browser caching of existing service workers

### ISSUE THREAD

**Issue by andeplane** [jupyterlite/jupyterlite#1335]
## Description
I haven't seen this problem explicitly be mentioned, but maybe https://github.com/jupyterlite/jupyterlite/issues/815 is the same one.

When there is a new version of the service worker, there is no information that prevents caching in the browser. The URL fetched [here](https://github.com/jupyterlite/jupyterlite/blob/main/packages/server/src/service-manager.ts#L45) is e.g. https://jupyterlite.readthedocs.io/en/stable/_static/service-worker.js, e.g. no information about the version. 

This means the preloaded service worker will be the one installed, and there is thus a potential change in the API between client and service worker.

## Reproduce
1) load jupyterlite
2) deploy a breaking change in service worker
3) load jupyter lite again, it crashes

We are using JupyterLite and have seen problems when bumping to a new version due to this. 

## Expected behavior
Old service worker should be unregistered to get the latest version.

## Context

- JupyterLite version: 0.2.3
- Operating System and version:
- Browser and version: Chrome 122.0.6261.94

**Comment by jtpio** [comment]
> When there is a new version of the service worker, there is no information that prevents caching in the browser. The URL fetched [here](https://github.com/jupyterlite/jupyterlite/blob/main/packages/server/src/service-manager.ts#L45) is e.g. https://jupyterlite.readthedocs.io/en/stable/_static/service-worker.js, e.g. no information about the version.

There used to be hash in the file name of the service worker, but it was removed in https://github.com/jupyterlite/jupyterlite/pull/1159 because it was creating issue for downstream applications trying to reuse it, since the hash would depend on the JupyterLite version used for building the application.

Maybe this idea of hash should be kept, and instead but passed as a query argument? So requesting the service worker file would become https://jupyterlite.readthedocs.io/en/stable/_static/service-worker.js?v=123456789

**Comment by andeplane** [comment]
Yep, that is a god alternative to the proposal in #1336. I'm not sure about the life cycle of these service workers then though, if the old versions keep existing and maybe it is cleaner to unregister + register.

**Comment by jtpio** [comment]
> maybe it is cleaner to unregister + register.

Yeah, since the main motivation for having the service worker in the first place was to support accessing files from a kernel.
