### ISSUE TITLE
jupyterlite-sphinx

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite#149]
It would be super-duper great if we started a jupyterlite-sphinx project.

It would be a crossover of jupyter-sphinx and thebelab, but running entirely in the browser.

One feature of such tool that I would like to see is being able to pre-render the output of the cells when generating the docs, just like jupyter-sphinx does it ([like here](https://ipyleaflet.readthedocs.io/en/latest/api_reference/popup.html)). This way we don't have to execute the cell when the user opens the docs. But if the user wants to edit the cell and re-execute, they can thanks to pyolite!

**Comment by bollwyvl** [comment]
Yes, we should support (and dogfood) some baseline integration as soon as possible. Since we'll be ready to support multiple python packages, I'd anticipate making it a separate package, which would depend on `jupyterlite`, because I don't _really_ trust `extras`, and people's docs dependencies are often... special. But (for now) the code could live here.

We can reuse the `LiteManager`, and hoist the `LiteBuildConfig` values to extension configurables... that is a frigging mess, but hopefully can be kept accurate with automation.

Additionally, I don't see why we wouldn't offer a `jupyterlite-sphinx-theme`, which took over the _whole_ `_build` folder (not just `_build/_static`) and made all your built content and sources available in a browseable file tree. It could keep the full path structure, for SEO purposes.

Of course, it might not be a full lab by default, and instead be a very lightweight, `retro`-like UI, but _with_ collapsible/draggable site sidebars, a custom main menu, etc. Would be a fun design challenge for sure!

> pre-render the output of the cells

For the _specific_ case of `pyolite`, if it mirrors the `IPython` namespace closely enough (or one has good as-needed patches), it would be possible to generate those with semi-faithful content. However, I don't see pre-rendering the docs happening in the _general_ browser kernel case, as we won't always have server-side kernels capable of creating outputs, and I'd really prefer _not_ putting any headless browser cruft into this repo outside the initial scope of #6. If we ever do, I would sure-as-shooting argue for a `qt`-based solution, not `nodejs` or `pyppeteer`. But from the #147 `build` perspective, that's going to be _strictly_ an _a priori_ piece of information, as executing notebooks creates a _lot_ of entropy.

**Comment by jtpio** [comment]
This would also help fix https://github.com/jupyterlite/jupyterlite/issues/369

**Comment by martinRenou** [comment]
> Of course, it might not be a full lab by default, and instead be a very lightweight, retro-like UI

Actually, it would be nice to have the option between having a full lab UI, a simple retrolab UI, and no lab UI at all.
For the latest option, I see an equivalent of the nbsphinx package, but with live cells powered with Pyolite

**Comment by martinRenou** [comment]
Thinking a bit more about it, I thought it could be nice to have multiple options for this.

## pyolite-sphinx

A `jupyter_sphinx` equivalent (or building on top of it), that could provide a sphinx directive that allows rendering executable code cells:

```rst
.. pyolite-execute::

   print('Hello from Pyolite!')
```

I am personally very excited by such approach. This would allow documentation like [ipyleaflet's one](https://ipyleaflet.readthedocs.io/en/latest/api_reference/tile_layer.html) to be slightly modified so that it provides executable cells.

## jupyterlite-sphinx

As commented by @bollwyvl in https://github.com/jupyterlite/jupyterlite/issues/369#issuecomment-933610026, this could provide a Sphinx extension that generates a fully-fledged JupyterLite deployment, that would be an approach to very easily setup and deploy JupyterLite on readthedocs.

**Comment by martinRenou** [comment]
Reading a bit more about all this, I realized jupyter-sphinx actually has a Thebelab option that allows making cells editable and executable https://github.com/jupyter/jupyter-sphinx/blob/master/jupyter_sphinx/thebelab.py. So I guess the `pyolite-sphinx` extension I mention in the above comment could actually be `jupyter-sphinx + thebelab + pyolite support in thebelab` (related to https://github.com/stevejpurves/thebe/pull/40).

**Comment by jtpio** [comment]
Probably `pyolite-sphinx` will be very related to the ongoing work in https://github.com/stevejpurves/thebe/pull/40 indeed.

Maybe we can start with `jupyterlite-sphinx` first. This would be really handy to generate docs sites. And would be a great alternative to Binder for many JupyterLab extensions and Jupyter Widgets repos.

**Comment by martinRenou** [comment]
> Maybe we can start with jupyterlite-sphinx first. This would be really handy to generate docs sites

What is unclear to me is what would a `jupyterlite-sphinx` tool bring that `jupyter lite build` cli doesn't already bring?

**Comment by jtpio** [comment]
Maybe something that would abstract away some of specifics of the RTD `conf.py`?

The current config works but can be a bit daunting at first: https://github.com/jupyterlite/jupyterlite/blob/main/docs/conf.py

Hopefully we find a way to enable other repos to do the same so it just works, without copy pasting the `conf.py`. Which is also the main motivation behind https://github.com/jupyterlite/jupyterlite/issues/369.

**Comment by bollwyvl** [comment]
>>> what would a jupyterlite-sphinx tool bring that jupyter lite build 
>
>> abstract away some of specifics of the RTD

Right, MVP is just being able to say:

```
# requirements.txt
sphinx >=3,<4
jupyterlite-sphinx
```

And get either a failed install, or a known-good configuration (I tire of some of the recent sphinx issues).

```py
# conf.py
extensions = [
  "sphinx-jupyterlite" # or whatever
  # ...
]
```

...and have it "Just Work" when you `sphinx-build`, where "Work" means, "has deployed lab and retro". By default, it would treat the parent of `conf.py` as the `lite_dir`, so all of the well-known file stuff would work, but it could have a few knobs so that you could get away with just specifying `jupyter-lite.json` and `jupyter_lite_config.json` right in conf.py, if you so desired, and/or specify the "target," (e.g. `archive`  or `check` instead of `build`). Some of the config, if unspecified, we could re-use, such as `faviconUrl`, etc.

Some follow-ons that might not be in-scope of the core repo:
- Use knowledge of the generated contents, wheels, etc. that we index to making toc references for all of the files and headers of e.g. `.md` and `.ipynb` so that one could deep link into a specific part of a file, with a running kernel.
- Use the sphinx-generated search index to make a rip-roaring search interface inside lab, powered by the existing index, which can open up multiple (versions of) files within lab tabs
- offer a slide-out iframe "drawer" of a retro console that can be controlled by...
  - ...an iframe `postMessage` API that basically proxies `exposeAppInBrowser` so that you can scroll through a long-form document and see the code executed
    - the thebe model is... not exactly out of reach, but would take a lot of plumbing to support "correctly" w/r/t labextensions

**Comment by tchaton** [comment]
```py
.. pyolite-execute::

   print('Hello from Pyolite!')
```

This would be fire !!!

I went through the documentation and after trying for several hours, I didn't understand how to use Jupyterlite with Sphinx. Any YouTube video showing all the steps to get there?

Best,
T.C

**Comment by martinRenou** [comment]
I'm iterating a bit on jupyterlite-sphinx, adding a directive for replite that allows to write:

```rst
.. replite::
   :kernel: python3
   :toolbar: 1
   :theme: JupyterLab Dark

    print('Hello, World!')
```

See https://github.com/martinRenou/jupyterlite-sphinx
And https://jupyterlite-sphinx.readthedocs.io/en/latest/

**Comment by bollwyvl** [comment]
Fun stuff!

**Comment by bollwyvl** [comment]
Let's continue further on https://github.com/jupyterlite/jupyterlite-sphinx/issues
