### ISSUE TITLE
Reorganize the examples directory

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#168]
Now might be a good time to reorder notebooks in the examples directory

_Originally posted by @martinRenou in https://github.com/jtpio/jupyterlite/issues/156#issuecomment-863861029_

**Comment by bollwyvl** [comment]
At present, we have a lot of vertical space, but the default view is rather narrow (we could default it to larger, perhaps, but might need workspaces #139). Also, since we're thinking of renaming pyolite, I propose we just go with the canonical file extension, (e.g. `js`, `py`) a top-level group, and an (optional) specific like:

```
- _GALLERY_.ipynb
- js - basics.ipynb
- p5 - basics.ipynb
- py - basics.ipynb
- py - widgets.ipynb
- py - widgets - bqplot.ipynb
- py - widgets - leaflet.ipynb
```

The idea on the `_GALLERY_`: might need #139 (or we can fudge it), but having a default opening page that showed pictures of all the notebooks would be super helpful: if you don't know what `ipyleaflet` is, a picture of a map would get the point across quickly. for now, we could hand-jam it, but eventually (#6) this entire file could be generated, including screenshots.

**Comment by psychemedia** [comment]
A quick sketch of a possible new structure (the data dir should check relative file loading and also make the same data file more sensibly available across kernel subdir demos), but I ran into issues with the `jupyter lite build` not behaving as expected (`ipywidgets` fail to render?). I'd quite like to make sure any PR on reorganised examples meshes with an updated `jupyterlite-demo` walkthrough that I'll do alongside, but as it stands, my local demo fails on the `ipywidget` containing notebooks. I also need to sign off for the w/e now, so will have to return to this next week...

![image](https://user-images.githubusercontent.com/82988/124273512-04327800-db38-11eb-9a88-c63b4079ecc6.png)

**Comment by jtpio** [comment]
> I ran into issues with the `jupyter lite build` not behaving as expected (`ipywidgets` fail to render?)

Right, looks like this is tracked in https://github.com/jtpio/jupyterlite/issues/209

**Comment by jtpio** [comment]
Maybe we could start offloading some of these dependencies and examples to https://github.com/jupyterlite/demo, to avoid increasing the build time on the ReadTheDocs previews?

And keep https://jupyterlite.github.io/demo/ as the "stable" demo (using a released `jupyterlite`), and https://jupyterlite.rtfd.io/en/latest/try/lab  be the "nightly". This could help ensure snappier previews here in this repo for development.

Originally mentioned in https://github.com/jupyterlite/jupyterlite/pull/238#issuecomment-879218663

**Comment by bollwyvl** [comment]
The cost of each additional extension is down to:

- (maybe) downloading the conda package (they cache well)
- unpacking it
- copying it
- re-packing it with everything in the docs app archive (which we _could_ stop doing)

I think running too-lite (ha) of a ship introduces the risk of a small change which would be harder to test interactively if it has to be created from scratch... and might lead to too-early-merging of a feature/upstream update.

We can also use them as _data_ in the documentation, e.g. with `depfinder`

**Comment by bollwyvl** [comment]
Seems kinda done now.
