### ISSUE TITLE
Be more intentional about some of the imports hacks

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#227]
Could we, to the extent possible, be more intentional about some of the imports hacks so that these things run under `nbconvert --execute` and `nbval`? e.g.

```py
try:
    import pyolite
    # do hacky things
except ImportError:
    pass
```

It's also worth adding a `<details><summary>Limitations</summary>...</details>` markdown cell above any cells like these to all of our examples. Totally aside, but dang i sure wish there was a good markdown flavor that supported `details`...

_Originally posted by @bollwyvl in https://github.com/jtpio/jupyterlite/issues/219#issuecomment-874920456_

**Comment by bollwyvl** [comment]
> from https://github.com/jtpio/jupyterlite/pull/226#issuecomment-875613284
>>  the added overhead introduced by the new PIL import, but if it's significant then we should probably start thinking of a different approach indeed.

It's more of a death-by-a-thousand-cuts... because `pip`, every additional package requires:

- a call to pypi for the metadata (unless it's already pre-built, as is the case for PIL)
- a fetch of the `whl` (and `.data` in the case of the PIL because not conda)
- a recursive descent into every dependency and transient dependency (none, happily, in the case of PIL)
- unpacking the wheel

If you want and expect this, because `matplotlib` (or especially `pandas`) is slow to import _anyway_ on e.g. binder (which has stupid fat pipes to the internet), hooray! User expectation not violated. 

If you just want to `1+1`, boo... worse still is if That Next Request gets gummed up, and your kernel just doesn't come come up, which happens _fairly_ frequently to me when demoing in less-than-ideal settings (phone) with a cold cache (PRs).

At any rate, if we formalize post-install patches as e.g. `entry_points`, I could imagine getting some of these into upstreams.

Pre-install patches are... harder, and we'd have to pretty much own those, and do some `micropip` patches (:rofl: ) to Do The Right Thing.

**Comment by jtpio** [comment]
Closing as it's probably not that relevant anymore after https://github.com/jupyterlite/jupyterlite/pull/911.

We can track potential other improvements in https://github.com/jupyterlite/pyodide-kernel.
