### ISSUE TITLE
Confused about how to add extension & python packages

### ISSUE THREAD

**Issue by qqdaiyu55** [jupyterlite/jupyterlite#316]
### Problem

Hi there, I want to add my custom extensions & add extra python packages for jupyter lite.
I checked the [doc](https://jupyterlite.readthedocs.io/en/latest/configuring.html#adding-extensions) and some issues about how to add extensions, but sill does not work, could you please help with it or provide with a sample site repo?

For adding custom extension:
1. `jupyter lite init`, I will see `_output` and `.jupyterlite.doit.db` in root folder.
2. I create `lab/extensions/` in root folder, and add some extensions like `jupyterlab_templates`
3. Run `jupyter lite build`. **However, these extension files won't be copied to `_output/lab/extensions/`.**
4. I thougth I need to create a json config file in somewhere to help jupyter lite to locate these custom extensions? Didn't find doc for that.

For environment extensions:
1. I installed `jupyterlab_templates` and `jupyterlab-sidecar` with `pip` and `jupyter labextension`.
2. Run `jupyter lite build`. The extension files are copied to `_output/lab/extensions/`, but nothing changes in `_output/lab/build`
3. Run `jupyter lite serve`, **the extensions didn't take effect.**

For install extra packages:
1. Currently I have to install packages in notebook with `await micropip.install("foobar")`
2. I checked some issues, like [this one](https://github.com/jupyterlite/jupyterlite/issues/151), just want to confirm that: there is no way to pre-install extra python packages for now right?

---
FYI my setting
- Jupyter lite version: v0.1.0a6
- System: Windows 21H1
- Python: 3.9.1
- pip version: 20.2.3

**Comment by jtpio** [comment]
Thanks @qqdaiyu55.

> could you please help with it or provide with a sample site repo?

There is this demo repo, which uses the version of `jupyterlite` published to PyPI: https://github.com/jupyterlite/demo

With the steps to generate the website with the lab extensions: https://github.com/jupyterlite/demo/blob/0183bbf90c12b3a49fa513c7ce5fe25d6c0a441f/.github/workflows/deploy.yml#L21-L31

At the moment this is the simplest and recommended way for adding extensions to a JupyterLite website.


>     2\. I checked some issues, like [this one](https://github.com/jupyterlite/jupyterlite/issues/151), just want to confirm that: there is no way to pre-install extra python packages for now right?

That's right. The goal is to make it possible to have a fully self-contained deployment that does not depend on external resources like PyPI or CDNs. There is some work-in-progress happening in #310 as a first step.

**Comment by qqdaiyu55** [comment]
Thanks @jtpio 
From the demo repo I can see some example notebooks, but still do not know how to configure my own web app for extensions. Especially for problem **For adding custom extension:** I mentioned, I still have no idea on how to make extra extensions work.

**Comment by bollwyvl** [comment]
> For adding custom extension

The environment-based way you found is the least peril-fraught, as, for example, by depending on `jupyterlab-sidecar`, `pip` or `conda` is _also_ pulling in a _compatible_ `@jupyter-widgets/jupyterlab-manager` from `jupyterlab_widgets`. At least until #310 makes it _very_ straightforward to keep labextensions and kernel packages compatible, we won't be offering any kind of package-manager-style solving capability, because down that path lies madness.

Otherwise, if you need to get _really_ specific, using the `federated_extensions` key in [`jupyter_lite_config.json`](https://github.com/jupyterlite/jupyterlite/blob/main/examples/jupyter_lite_config.json) is recommended. We use conda, but wheels URLs (and paths) also work. So if you're building an extension (e.g. with `jupyter labextension build`) and a lite site "hot", you just specify the path to [your locally-built `.whl`](https://github.com/deathbeds/ipydrawio/blob/master/demo/jupyter_lite_config.json).

**Comment by qqdaiyu55** [comment]
@bollwyvl  @jtpio  BTW I found it does not support auto-complete yet, any plan to support it thx?

**Comment by jtpio** [comment]
> @bollwyvl @jtpio BTW I found it does not support auto-complete yet, any plan to support it thx?

Normally it should be supported. Maybe you are facing this issue? https://github.com/jupyterlite/jupyterlite/issues/259
