### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'debu'

### ISSUE THREAD

**Issue by stevejpurves** [jupyterlite/jupyterlite#332]
## Description

When running jupyterlite build locally using mulitple contents arguments, and files that are already resolved(?) causes an error.

`AttributeError: 'Logger' object has no attribute 'debu'`

Looks like a typo on:
https://github.com/jupyterlite/jupyterlite/blob/main/py/jupyterlite/src/jupyterlite/addons/contents.py#L117

## Reproduce

On the command line, call `jupyter lite build` with at least 4 contents arguments
My exact command to hit the error was:
```
jupyter lite build --contents 1402_Smoothing_surfaces --contents 1404_Euler_deconvolution --contents 1406_Make_a_synthetic/ --contents 1408_Evaluate_and_compare_colormaps/
```

obviously a typo in the code

- JupyterLite version: 0.1.0a6
- Operating System and version: Mac OS Big Sur
- Browser and version: n/a

<details><summary>CLI Output</summary>
<pre>
Traceback (most recent call last):
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/jupyterlite/addons/contents.py", line 24, in <lambda>
    pprint.pformat([str(p[0]) for p in self.file_src_dest]),
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/jupyterlite/addons/contents.py", line 24, in <listcomp>
    pprint.pformat([str(p[0]) for p in self.file_src_dest]),
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/jupyterlite/addons/contents.py", line 117, in file_src_dest
    self.log.debu("Already populated", resolved)
AttributeError: 'Logger' object has no attribute 'debu'
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @stevejpurves for catching this :+1: 

> Looks like a typo on:

Would you like to open a PR? Thanks!

**Comment by bollwyvl** [comment]
Yerp, definitely my screwup there. :blush: 

Of note, though: if you hit that code, it means that some of your `--contents` are clobbering _other_ contents. Each entry is treated as a "contents root" which would be combined with the others. We kinda had to do it that way to support multiple files. So if some of those directories contain a `index.ipynb`, only the _last_ one will be present in your output. 

I can _highly_ recommend using a `jupyter_lite_config.json` rather than trying to get the CLI "just right", as we do on the [examples](https://github.com/jupyterlite/jupyterlite/blob/main/examples/jupyter_lite_config.json) that populate these docs.
