### ISSUE TITLE
Add an overview diagram

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#34]
It would be nice to have an overview diagram in the readme, to get an idea of how it works.

And also to illustrate the "server app" running as another Lumino application.

**Comment by bollwyvl** [comment]
Hooray diagrams! How do folk feel about the diagrams living in the drawio editable SVG format?

![](https://raw.githubusercontent.com/gist/bollwyvl/58ea3c2889fb0696d1008a1831527c52/raw/0361215c1fdf37ac6d867f3453bc63aa114c98eb/jupyterlite.dio.svg)

> yeah, there's some font nonsense, but that's mostly github...

My interest is several-fold: 
- it's an _acceptable_ place to draw architecture diagrams and mockups, but there aren't a lot of examples of them across the jupyter community
- being able to use [ipydrawio](https://github.com/deathbeds/ipydrawio) in the jupyterlite would be _quite_ nice, as all the fancy interactive plugins would work (e.g. collapsible groups, links, etc) that are lost in the otherwise-excellent static export

**Comment by jtpio** [comment]
> How do folk feel about the diagrams living in the drawio editable SVG format?

Those are great! Even the png with embedded metadata is really useful to have a self-contained diagram.

> being able to use ipydrawio in the jupyterlite would be quite nice

Absolutely. Maybe this will "just work" after adding support for ipywidgets? (also being discussed in https://github.com/jtpio/jupyterlite/issues/18)

**Comment by bollwyvl** [comment]
>  png with embedded metadata

It's true: the image diff is nicer on github than with svg (for whatever reason). But more broadly, I'm _really_ interested in ending up with solid SVG, as it's more accessible, prints better, looks better on 4k screens, etc. A killer feature i haven't yet figured out is making the links you can put on individual elements become "real" svg `xlink` attributes, as being able to click on a diagram and jump to (a line in) a file would be _wonderful_ for these kinds of things.

> support for ipywidgets

Nah, just needs the documentregistry/mime renderer machinery! The Jupyter Widget is pretty dumb, right now, as it just speaks (crazy) XML and (also crazy) configuration JSON. 

To the nuts-and-bolts of including ipydrawio: I don't see _quite_ yet how to ram some `federated_extensions` into `pageInfo`, and lemme tell you... you _don't_ want 5000+ design assets files (70mb) in every "lite" build. To include it in a dev/environment demo, I can really only support the `pip` or `conda` installation mechanism, predictably, today... I'm not even testing it as a source extension :rofl:, as even back in the day it would occasionally crash webpack.

**Comment by jtpio** [comment]
Closing as fixed by #278 with a follow-up issue in #279
