### ISSUE TITLE
Easier startup from the README.md

### ISSUE THREAD

**Issue by richtong** [jupyterlite/jupyterlite#436]
### Problem
It is very hard from the initial README.md to know exactly what to do to make this work. For instance, how to get this to run with
-->

### Suggested Improvement

I'm happy to contribute a README.md that is more "for dummies" so you don't have to go to the template examples json and the developer documentation just to get a single Jupyter notebook that you already have and edit it.

**Comment by jtpio** [comment]
Thanks @richtong.

> I'm happy to contribute a README.md that is more "for dummies" so you don't have to go to the template examples json and the developer documentation just to get a single Jupyter notebook that you already have and edit it.

If you would like to open a PR that would be great, thanks!

**Comment by jtpio** [comment]
There has been some documentation improvements to the quickstart guides in https://github.com/jupyterlite/jupyterlite/pull/641.

Closing since they are now available in https://jupyterlite.readthedocs.io/en/latest/quickstart/index.html. Feel free to open a new issue or edit the README.md if needed, thanks!
