### ISSUE TITLE
Populate notebook data using in browser api

### ISSUE THREAD

**Issue by alisman** [jupyterlite/jupyterlite#458]
I would like to give my app's users the ability to spawn a PLite notebook populated with data they have filtered in my app.  I will host the static (empty) notebook.   I can see that PLite exposes an api in browser that seems like it could be used to accomplish this (add files) but I wasn't able to crack it.   Can anyone help?  Just to be clear, I would open PLite in another tab and then call its api from the parent tab.

**Comment by alisman** [comment]
I believe I figured this out like so:
`jupyterapp.serviceManager.contents.save("/data/hello.json", { content:{ ... } })`

**Comment by bollwyvl** [comment]
Yes, if you're serving from the same domain, that's a fine way to do it using the built-in techniques and high-level APIs. A lot of extensions (including the built-ins) also offer a lot of their capabilities off of `jupyterapp.commands`... indeed, if you want a notebook, most of these [commands already exist](https://discourse.jupyter.org/t/how-to-load-sample-file-into-jupyterlab/12666/2).

If you want more control (or access), you can leave yourself as much room as you need with a custom labextension which can reach in and get access... once you get a working extension, it can be added to the `federated_extensions` during `jupyter lite build`. 

Some cost/benefits to a custom labextensions:
- you have to do some more typescript
  - if the underlying typescript changes, you'll probably be warned of it _at build time_ rather than deployment time
- such an API could be defined over the [`postMessage` API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) which can even work _relatively_ securely between domains. 
  - such an API is very _unlikely_ to be added to JupyterLab core, as there are as many malicious ways to use it as nifty.

**Comment by jtpio** [comment]
> I believe I figured this out like so:
> jupyterapp.serviceManager.contents.save("/data/hello.json", { content:{ ... } })

Also, this is enabled on the demo site (https://jupyterlite.rtfd.io/en/latest/try/lab) because `exposeAppInBrowser` is set to `true` here:

https://github.com/jupyterlite/jupyterlite/blob/7b322c80125d51b393721ca0a28bf2bf432484e5/examples/jupyter-lite.json#L6

You would have to set that flag via `jupyter-lite.json` for your own deployment too.

**Comment by alisman** [comment]
Thanks @bollwyvl and @jtpio.    FYI, i am working on an integration with cBioPortal, which is a visualization/analysis platform for cancer data.  The idea is that users would be able to spawn a lite window with whatever data they happened to have queried/filtered in our tool.

**Comment by bollwyvl** [comment]
@alisman that's a lovely use case. I guess the key distinction would be: when hosted on the same domain there's a risk of abuse (slightly moreso than the browser console) from giving folks an executable environment. So if have logged-in users, they can do whatever in lite they can as a web user, given enough care.

**Comment by alisman** [comment]
@bollwyvl curious why you think moreso than the browser console?  
btw, i do imagine users wanting to share scripts so that's indeed a reason to put it on another domain and use a postMessage layer to manipulate notebook from parent app.

**Comment by bollwyvl** [comment]
So anyhow: open source, `NOT FIT FOR ANY PURPOSE`, get what you pay for, yadda yadda: we're trying to be a bit conservative on what is enabled/made easy by default, but as the deployer, you can do whatever you want! We're trying to give everybody the tools they need to deploy novel interactive computing experiences at scale.

But, not to be too preachy, deploying any Jupyter tool (or interactive computing, really) on someone's behalf represents a balance between empowering and protecting that user (and their data). Browsers _could_ offer a powerful, on-by-default console, but don't... firefox even has a captcha-style "I AM SURE" thing in their console as a last ditch defense against drive-by copy/pasta attacks.

With lite, some features such as `?path=` will automatically open an arbitrary path... in a "regular" deployment, only paths that the deployer put there (or that the user made) would exist, and this is pretty safe. But some suggestions like #430 would make that... really hard to protect. But you could _still_ do it as an extension... but we have no business making that a default.

In custom deployments (e.g. that replaces contents #315) co-deployed with "the goods" of an authenticated application, the `?path` feature could be used to send an unsuspecting user to a malicious file, e.g. `/notebooks/bad-user/malicious.ipynb`, but in the right setting would be _awesome_. Similarly, the [RTC capability](https://jupyterlite.readthedocs.io/en/latest/rtc/) is even crazier, but too awesome to not do (but not awesome enough to turn on by default).

Even _rendering markdown_ can sometimes cause XSRF issues, and a kitted out jupyterlab goes _far_ beyond that.

**Comment by alisman** [comment]
@bollwyvl I am running into an issue where when use 
`jupyterapp.serviceManager.contents.save("/data/hello.json", { content:"some tab delimited string" })`. 
i get a file containing that string with quotes around it (and \t javascript tab escape) for the tabs.  Any idea what I'm doing wrong?

**Comment by bollwyvl** [comment]
Have a look at more of the options of the second argument of [`save`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/contents/index.ts#L37). It might be it's defaulting to `json`... and you might need to voerload `type`, `mimetype` and/or `format`. It's also worth looking about in the codebase for other uses of that type (`Contents.IModel`), most easily done in a typescript-aware editor/IDE with _Go to References`, etc.

**Comment by alisman** [comment]
Thanks! you were right.  I needed to send format and/or mimetype.  Works great now

**Comment by bollwyvl** [comment]
Closing as apparently resolved.
