### ISSUE TITLE
How to access browser localStorage from notebook

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#581]
Currently a user has access to the browser's [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), which can (currently) be used to read/write files visible in the UI (as described [here](https://github.com/jupyterlite/jupyterlite/discussions/91#discussioncomment-2440964)):

```py
import js
IDBOpenDBRequest = js.self.indexedDB.open(DB_NAME)
# etc
```

But I could not find a way to access other types of browser storage:
+ [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)
+ [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)
+ [cookies](https://developer.mozilla.org/en-US/docs/Web/API/CookieStore)

Is it possible ? planned ?

I would argue such low level capabilities foster creativity and maybe are not that difficult to provide (?)

NOTE: I understand from @bollwyvl [here](https://github.com/jupyterlite/jupyterlite/discussions/91#discussioncomment-2442854) that file system access is very much a WIP and should be given a proper well documented API. But allowing low level access can still enable people to do some pure web stuff (For example, I am currently trying to run a corporate OAuth2 upon page load, with a tweaked index.html file, then store the token to some web storage - indexedDB for now - and make it available to python code to make requests to protected APIs)

**Comment by bollwyvl** [comment]
Please have a look at #315 and #463 , where we're gathering some insights about storage and kernels.

Basically: the scope of jupyterlite is guided by, but not limited to, today's pyodide kernel implementation: anything we do needs to work there, but can't _only_ work there. Indeed, it will be a good day when much of the complexity around python can be shifted out of this repo, a la #386 . Further, the extent to which customizations also work/can be tested in "stock" jupyterlab and kernels the better. 

our goal on the above linked tickets is to only require implementing a single [storage backend as a liteextension](https://github.com/jupyterlite/serverlite-cookiecutter-ts), and then have that be shared by both the Lab/Retro UI as well as different kinds of kernels. If every customization has to do stuff at all of those levels, it's going to be very hard to keep things running over time.

> not that difficult to provide

None of the things everyone wants, by themselves, are probably _that_ difficult, but they impact each other in different ways. PRs welcome: but there are a number of things we probably just aren't going to merge at this time... e.g. autorunning code, highly-coupled kernel/storage solutions. However, well-argued extension points which can be used by extensions to achieve interesting effects are much more likely to be reviewed and merged.

> other types of browser storage ... possible ... planned

anything that can be accessed from within the WebWorker is fair game, both to you and users. whether that is the same thing that the UI main "thread" sees is an entirely separate question. In the case of what you mention: _no_, those APIs are not available to WebWorkers.

The reasoning behind the WebWorker is to keep (sometimes _very_) slow computation off the main UI: all interactions locking up for 20s while some webassembly loads feels much more broken than a more standard UI process.

Indeed, on #386, there may well be a compelling use case for doubly-wrapping kernels, e.g. a webworker inside a "headless" iframe on a separate domain, so that the _only_ way in and out is via postmessage.

The best option _today_ to make some of those available would be:
- implement ipywidgets that emulate some of these behaviors
  - [ipylab](https://github.com/jtpio/ipylab) has some good examples
- implement a custom lite kernel:
  - a number of other ones in [this org](https://github.com/jupyterlite)
  - there are a few [in the wild](https://github.com/deathbeds/pidgy/tree/main/lite/jupyterlite-pidgy)

>   tweaked index.html

good luck with that route, but as your complexity rises, certainly consider whether you could achieve some of these effects within the standard [labextension workflow](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html) and tooling, which will be more robust over time.

eventually, we hope to have some better offerings of the cookiecutter, as well as more data-driven approaches for common effects, but so far, the common patterns needed have not yet emerged.

**Comment by oscar6echo** [comment]
> In the case of what you mention: no, those APIs are not available to WebWorkers

Ok. Clear.  

Thx for the swift reply and broad description. I do not hint at any change in the design decisions which seem very reasonable.  

> "tweaking the /lab/index.html" 

While it sounds dangerously hackish, I would argue this is a potentially very rich avenue. I tested injecting a JS lib to manage OAuth and save the resulting token in separate indexedDB - the lib also refreshes it every few minutes. It works fine.  See below.

The point I would like to demonstrate is that having a JS lib living outside / next to JLite, using IDB as a standardized communication channel, allows to keep things very simple / readable by non Jupyter specialists. It enables to create data in pure JS and make it available for read in a kernel, but also to react on changes in the IDB.

To enable this capability there would just need to create a placeholder in the index.html for people to potentially use. However this can be done by just replacing the default lab/index.html by a custom one.

Just food for thought.

```html
<!DOCTYPE html>
<html>
  <head>
    <title>JupyterLite</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

   <!-- START CUSTOM -->
   
   <script src="https://corp-oauth2-lib"></script>
   <script>
      // custom JS code to initiate the OAuth workflow
   </script>

    <script src="https://unpkg.com/dexie/dist/dexie.js"></script>
    <script>
        const db = new Dexie("CORP");
        db.version(1).stores({secrets: ""});
        db.open()
          .then(async (db) => {
            await db.secrets.clear();
            await db.secrets.add(
              {
                created: new Date().toISOString(),
                token: corpLib.getToken(),
              },
              "auth"
            );
          })
          .catch((err) => console.log(err));
      }
    </script>

    <!-- END CUSTOM -->

    <link
      id="jupyter-lite-main"
      rel="preload"
      href="../build/lab/bundle.js?_=66914db"
      main="index"
      as="script"
    />
   
    <script
      id="jupyter-config-data"
      type="application/json"
      data-jupyter-lite-root=".."
    >
      {}
    </script>
    <script>
      (async function () {
        const { pathname, origin, search, hash } = window.location;
        if (pathname.match(/(index.html|\/)$/) == null) {
          window.location.href = `${origin}${pathname}/${search}${hash}`;
          return;
        }
        await import("../config-utils.js?_=66914db");
      }.call(this));
    </script>
  </head>
</html>
```

**Comment by oscar6echo** [comment]
Closing as the answer is above.
