### ISSUE TITLE
Can’t read csv

### ISSUE THREAD

**Issue by brooksw** [jupyterlite/jupyterlite#592]
Hi, 

I have a number of notebooks that run just fine in Juno using a Pythia 3 kernel. 

I went to show my students your formerly wonderful site, but, NONE of my notebooks work in JupyterLab.

The failure is at the point where I use df = pd.read_csv("25g5N_28Oct.csv") . It throws a file-not-found error. I tried all kinds of path variations and other changes. This is the specific error:

/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.

It is a pity you chose to force people to test an experimental kernel, with no available alternatives. Please help me to fix the problem.

Thanks, 

 - Will

**Comment by bollwyvl** [comment]
The (free) jupyter.org/try service has started using jupyterlite to reduce
the impact on the (also free) mybinder.org. both of these are covered by
donations, which are not infinite.

try constituted a large proportion of the overall traffic, and transferring
some of the examples improves the availability of the service overall
within the same budget.

jupyterlite will at some point support your use case, but relies on free
labor to get new features.

In the meantime, your best option is probably to set up a GitHub repo or
gist which you can use directly with mybinder.org. this will help ensure
your data and dependencies are cached and ready to use.

Alternately, download jupyter software directly to your computer

**Comment by psychemedia** [comment]
@brooksw I feel your pain re: the fiddliness of working with files in an educational context, where the aim is on eg the subject matter of using `pandas` rather than the JupyterLite-specific mechanics of trying to actually get data into a dataframe.

I have been trying to collect and iterate on some recipes here, gathered mainly from issues and discussion threads in this repo where folk have managed to come up with workarounds. They are currently gather together here: https://github.com/innovationOUtside/ouseful_jupyterlite_utils

**Comment by brooksw** [comment]
Dear Tony, 

Thank you, I will take a look.

Best regards, 

 - Will

**Comment by jtpio** [comment]
Thanks all.

I think we can close this, since this is already being discussed in https://github.com/jupyterlite/jupyterlite/issues/119 and related issues and discussions. So we can keep the conversation in one place.
