### ISSUE TITLE
End to end testing

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#6]
There should be some end to end testing, ideally with galata: https://github.com/jupyterlab/galata

**Comment by bollwyvl** [comment]
Welp, over on [ipydrawio](https://github.com/deathbeds/ipydrawio/pull/57), I'm up to a mostly working site, and could _turn the knob_ to put  this under robotframework testing. I'm half inclined to:

- start testing in robot on that PR
- refactor those into another `robotframework-jupyterlibrary` [client](https://robotframework-jupyterlibrary.readthedocs.io/en/latest/KEYWORDS.html)

Further, over on we're starting to think about how to get a "RoboLite" running once #171 has relaxed some limitations... https://github.com/robots-from-jupyter/robotkernel/issues/72.

**Comment by bollwyvl** [comment]
I've got some [very basic, not super-indicative robot](https://github.com/deathbeds/ipydrawio/blob/master/atest/lite/Documents.robot) tests running `ipydrawio`. The [site](https://ipydrawio.readthedocs.io/en/latest/_static/lab/index.html) looks pretty good.

**Comment by datakurre** [comment]
FYI. We did get "RoboLite running" (https://github.com/robots-from-jupyter/robotkernel/issues/72). Some rough edges left, but looking good. https://robolite.readthedocs.io/en/latest/_static/retro/notebooks/?path=robolite%20-%20smoketest.ipynb

**Comment by bollwyvl** [comment]
Thanks for sharing @datakurre! It's certainly on me for not having proposed a robot complement to #258, but it's great to see robot represented in the lite space.

I think the potential for in-browser automation/test execution is a very interesting use case, and worth exploring. The other aspect, of demonstrating the wrapping of our pyodide kernel for other language runtimes, is also important for finding the places where we need to improve the extensibility at the typescript and python levels.

As pertains to _this_ issue: provided a change didn't break itself hard enough to prevent starting, we could use the environment to test itself (in a second, managed tab), one of the properties we had in e.g. robotlab. Sure, we'd have to re-implement the non-trivial API surface of one of the browser/REST API keyword libraries, and there would be some things we just couldn't do with JS, by design, but these challenges seem surmountable.

More broadly: a web site/application under development (aren't they all, though?) could _copy some files_ for a dev deployment and co-deploy a lite site, which would give devs/testers/power users the ability to create automation tools "inside the house." without individuals (or even IT) having to deploy complex automation infrastructure, fake/real browsers etc.
