### ISSUE TITLE
Deployment Documentation

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#67]
### Problem

It's still a little unclear how one would actually deploy and "own" jupyterlite.

### Proposed Solution

Add a _Deployment_ section which includes:
- how to configure
  - where to put a `jupyterlite.json` 
  -  JSON Schema 
- how to get the code
  - we could be shipping the tarball to the docs site, which is as good as any, for now
- configuring different SaaS providers
  - vercel
  - github pages
  - readthedocs
- on-premises
  - nginx?
  - inside other host apps
    - jupyterhub
    - jupyter_server (#41)
      - jupyter-server-proxy 
    - django?
    - fastapi?
    - flask?
  - how to configure CDN replacements (#45)

### Additional context

- #30 probably required before this is actually important

**Comment by jtpio** [comment]
Dumping some for Vercel in this issue:

- Create an account
- Run `vercel` from the repo locally to get the secrets, see https://github.com/amondnet/vercel-action#how-to-use for some details
- Add the action to the repo (see this repo, or add code snippet)
- There should be a comment on the next PR

**Comment by bollwyvl** [comment]
Started a skeleton (lots of TBD) for this on #58:
https://github.com/jtpio/jupyterlite/pull/58/files#diff-27ccda254fe500e13705e63554cdf4dcaf4c8b8e2fc74024f61776d407a30c56R1

**Comment by areeves87** [comment]
Very excited about this project. Had a lot of fun trying the jupyterlite demo notebooks out today!

I want to share an interactive jupyerlite notebook-style report with my colleagues in the near future. Will it be possible to provide a step-by-step guide for how to publish a jupyterlite notebook to amazon s3? Since s3 hosts static web pages and supports `application/wasm` content I suppose it's possible to do. But I haven't had time to figure out what exactly are the steps required.

**Comment by bollwyvl** [comment]
Yeah, there are a lot of distracting directions (e.g. #141) right now, but getting a minimal CLI out is probably more important. Once written, It's going to be much easier to keep _that_ documented in a semi-automatic way, e.g. `jupyter lite --help`, rather than a bunch of narrative docs. 

Once that works, it will be:

```bash
pip install jupyterlite <any labextensions you want>
jupyter lite init ./my-jupyterlite
cp <your notebooks> ./my-jupyterlite/files
jupyter lite build ./my-jupyterlite
```

...and the contents of `./my-jupyterlite` will be a ready-to-host site, on s3 or whatever. Shouldn't have any `nodejs` dependency. We can leave some hooks open, e.g. `jupyter lite publish --to s3` but that _implementation_ probably wouldn't live in this repo. 

Since #141 isn't going to be merged any time soon, maybe I'll switch gears and try and get something passable out re #41...

**Comment by jpivarski** [comment]
Rather than starting a new issue, I tried to find an issue that most closely matched what I'm trying to do. I'm either using the CLI incorrectly or encountering a bug. Feel free to export this comment to a new issue or ask me to do that.

I installed `jupyterlite[lab]` [because it is the most general](https://jupyterlite.readthedocs.io/en/latest/cli.html) (I already had JupyterLab installed).

```bash
% pip install --pre jupyterlite[lab]
```

My versions are

```bash
% jupyter lite --version
0.1.0a5
% jupyter lab --version
3.0.16
```

I made an empty directory and got into it.

```bash
% mkdir /tmp/some_directory
% cd /tmp/some_directory
```

Then I ran `jupyter lite init` in the directory to set it up.

```
% jupyter lite init
static:jupyter-lite.json
.  pre_status:static:jupyter-lite.json
    tarball:  jupyterlite-app-0.1.0-alpha.5.tgz 19MB
    output:   /tmp/some_directory/_output
    lite dir: /tmp/some_directory
    apps:     ('lab', 'retro')
archive:archive
contents:contents
lite:jupyter-lite.json
serve:contents
settings:overrides
.  status:archive:archive
[LiteInitApp] No archive (yet): some_directory-jupyterlite.tgz
.  status:contents:contents
    contents: 0 files
.  status:lite:jupyter-lite.json
[LiteInitApp]     jupyter-lite.(json|ipynb): 0 files
.  status:serve:contents
    will serve 8000 with: tornado
.  status:settings:overrides
    overrides.json: 0
static:output_dir
.  pre_init:static:output_dir
static:unpack
.  init:static:unpack
% ls -a
_output  ..  .jupyterlite.doit.db  .
```

I think that the next step is to `build` it. (I also tried without this step and got the same error message.)

```
% jupyter lite build
static:jupyter-lite.json
.  pre_status:static:jupyter-lite.json
    tarball:  jupyterlite-app-0.1.0-alpha.5.tgz 19MB
    output:   /tmp/some_directory/_output
    lite dir: /tmp/some_directory
    apps:     ('lab', 'retro')
archive:archive
contents:contents
lite:jupyter-lite.json
serve:contents
settings:overrides
.  status:archive:archive
[LiteBuildApp] No archive (yet): some_directory-jupyterlite.tgz
.  status:contents:contents
    contents: 0 files
.  status:lite:jupyter-lite.json
[LiteBuildApp]     jupyter-lite.(json|ipynb): 0 files
.  status:serve:contents
    will serve 8000 with: tornado
.  status:settings:overrides
    overrides.json: 0
static:output_dir
-- pre_init:static:output_dir
static:unpack
-- init:static:unpack
federated_extensions:copy:ext:nbdime-jupyterlab
federated_extensions:copy:ext:jupyterlab-jupytext
federated_extensions:copy:ext:@jupyter-widgets/jupyterlab-manager
.  pre_build:federated_extensions:copy:ext:nbdime-jupyterlab
.  pre_build:federated_extensions:copy:ext:jupyterlab-jupytext
.  pre_build:federated_extensions:copy:ext:@jupyter-widgets/jupyterlab-manager
federated_extensions:patch
.  post_build:federated_extensions:patch
% ls -a
_output  ..  .jupyterlite.doit.db  .
```

Now I try to serve it.

```
% jupyter lite serve
static:jupyter-lite.json
.  pre_status:static:jupyter-lite.json
    tarball:  jupyterlite-app-0.1.0-alpha.5.tgz 19MB
    output:   /tmp/some_directory/_output
    lite dir: /tmp/some_directory
    apps:     ('lab', 'retro')
archive:archive
contents:contents
lite:jupyter-lite.json
serve:contents
settings:overrides
.  status:archive:archive
[LiteServeApp] No archive (yet): some_directory-jupyterlite.tgz
.  status:contents:contents
    contents: 0 files
.  status:lite:jupyter-lite.json
[LiteServeApp]     jupyter-lite.(json|ipynb): 0 files
.  status:serve:contents
    will serve 8000 with: tornado
.  status:settings:overrides
    overrides.json: 0
static:output_dir
-- pre_init:static:output_dir
static:unpack
-- init:static:unpack
federated_extensions:copy:ext:nbdime-jupyterlab
federated_extensions:copy:ext:jupyterlab-jupytext
federated_extensions:copy:ext:@jupyter-widgets/jupyterlab-manager
-- pre_build:federated_extensions:copy:ext:nbdime-jupyterlab
-- pre_build:federated_extensions:copy:ext:jupyterlab-jupytext
-- pre_build:federated_extensions:copy:ext:@jupyter-widgets/jupyterlab-manager
federated_extensions:patch
-- post_build:federated_extensions:patch
serve:tornado
.  serve:serve:tornado
[LiteServeApp] WARNING | 

        Serving JupyterLite from:
            /tmp/some_directory/_output
        on:
            http://127.0.0.1:8000/

        *** Press Ctrl+C to exit **
        
WARNING:tornado.access:404 GET /jupyter-lite.ipynb (127.0.0.1) 0.98ms
WARNING:tornado.general:403 GET /lab (127.0.0.1): lab is not a file
WARNING:tornado.access:403 GET /lab (127.0.0.1) 0.48ms
```

But when I look at the webpage `http://127.0.0.1:8000/` it only displays this error message:

```
Traceback (most recent call last):
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 2576, in get
    self.absolute_path = self.validate_absolute_path(self.root, absolute_path)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 2780, in validate_absolute_path
    raise HTTPError(403, "%s is not a file", self.path)
tornado.web.HTTPError: HTTP 403: Forbidden (lab is not a file)
```

That's probably what made the warnings seen in the server process.

There _is_ a file named `lab` in the `_output` directory, if that's relevant.

```bash
% find . -name '*lab*'
./_output/lab
./_output/lab/extensions/nbdime-jupyterlab
./_output/lab/extensions/nbdime-jupyterlab/schemas/nbdime-jupyterlab
./_output/lab/extensions/@jupyter-widgets/jupyterlab-manager
./_output/lab/extensions/@jupyter-widgets/jupyterlab-manager/schemas/@jupyter-widgets/jupyterlab-manager
./_output/lab/extensions/jupyterlab-jupytext
./_output/lab/extensions/jupyterlab-jupytext/schemas/jupyterlab-jupytext
./_output/lab/build/themes/@jupyterlab
./_output/lab/build/schemas/@jupyterlab
./_output/retro/build/themes/@jupyterlab
./_output/retro/build/schemas/@jupyterlab
```

Am I doing something wrong? (In which case, a walkthrough in the documentation would be great; I can add it via PR if I ever get this working.) Or is this the right procedure, but is failing in this version?

I ultimately want to make this deployable as static HTML, without a specialized server (i.e. on S3, Netlify, GitHub.io, etc., without controlling the server), but I assume that running it in `jupyter lite serve` is a prerequisite. If this doesn't work, running it as static HTML won't.

Again, if this would be better as a new Issue (or a new Discussion), let's migrate it there. Thanks!

**Comment by bollwyvl** [comment]
yeah, trying going to `http://localhost:8000/index.html`. might be some redirect issues.

>  a walkthrough in the documentation

Welp, what we have right now is: https://jupyterlite.readthedocs.io/en/latest/cli.html

> running it in jupyter lite serve is a prerequisite. 

oh goodness, no! i didn't even want to put the `serve` thing in there, but the default `python -m http.server` is pretty insecure by default, and `tornado` doesn't have a CLI equivalent. The intent is entirely for the contents of `_output` to be _put in a place_ somewhere and Just Work, and indeed, we rely on ReadTheDocs and GitHub pages for our demos, which are about as bog-standard HTTPS hosts as you can get. I know nothing about netlify :shrug:

**Comment by bollwyvl** [comment]
also note that `nbdime` and `jupytext` are going to break pretty hard... and might take down your lab, once it _does_ open, depending on how tolerant they are of missing their server extension counterpart. i also wouldn't hold your breath on them working in the browser any time soon. 

at least off `main`, we've got a `--ignore-sys-prefix` (to avoid copying them) but extensions can be disabled with `overrides.json` or directly in `jupyter-lite.json`.

**Comment by jpivarski** [comment]
> > running it in jupyter lite serve is a prerequisite.
> 
> oh goodness, no! i didn't even want to put the `serve` thing in there, but the default `python -m http.server` is pretty insecure by default, and `tornado` doesn't have a CLI equivalent.

I guess that was the hint I needed. I didn't mean "prerequisite" as "you need it to run JupyterLite," but as "if it doesn't run in `jupyter lite serve`, then it won't work on a static HTML server." I wasn't going to try running it as static HTML if it didn't work in this way.

Considering that it's looking for a file/directory named `lab`, a key point is to serve from inside the `_output` directory. I wasn't doing that because I didn't see any indication on the CLI documentation page that I should. Running `jupyter lite serve` from inside the `_output` directory _still didn't work_, but

```bash
python -m http.server 8888
```

_did work_. (I could even import NumPy!) So the following would be a complete walkthrough and it would make the point that it _is_ just static HTTP:

```bash
pip install --pre jupyterlite[lab]

mkdir /tmp/some_directory
cd /tmp/some_directory
jupyter lite init
jupyter lite build

cd _output
python -m http.server 8888
```

Do you want me to make a PR with the above minimal example as a section on the CLI documentation page?

**Comment by bollwyvl** [comment]
`serve` will start the server in `--output-dir` (which defaults to `_output`)... as i'm saying, `http://localhost:8000/index.html` will work, we just need to ensure the trailing slashes, etc.

>  the above minimal example

We try not to write docs for things that leave people's machines open to the internet by default.

But actually, you don't even need to `init` _or_ `build`:

```
mkidr foo
cd foo
jupyter lite serve
```

(and a fixed default url) would do the thing. We can even add the annoying "autolaunch" thing, and redirect to the proper url, and require `--no-browser`, a la `lab` and `notebook`.

**Comment by jpivarski** [comment]
Okay, I drafted the text that would have helped me, but I won't open it as a PR if you're not interested.

https://github.com/jupyterlite/jupyterlite/compare/main...jpivarski:jpivarski/added-complete-example-documentation

Anyway, thanks for JupyterLite! It's awesome; I'll be following it and letting others know about it.

**Comment by bollwyvl** [comment]
Added https://github.com/jupyterlite/jupyterlite/discussions/261 to discuss adopting the auto-launch-a-browser behavior.

**Comment by bollwyvl** [comment]
@jpivarski we landed the improvement on #260, so now the text would say:

```
Serving JupyterLite from:
            /tmp/some_directory/_output
        on:
            http://127.0.0.1:8000/index.html

        *** Press Ctrl+C to exit **
```

thanks for the report. we'll hopefully get the rest of the issues sorted.

**Comment by ryan-williams** [comment]
I started working on a minimal "deploy your own Jupyterlite" repo, but eventually realized everything I needed was in [jupyterlite/demo](https://github.com/jupyterlite/demo). For my own understanding, I removed most of that repo, leaving just:
- one example notebook (in `content/`)
- `requirements.txt` (containing just `jupyterlite` and `jupyterlab`)
- GitHub Action for auto-deployment from `@main`

See [runsascoded/jupyterlite-demo](https://github.com/runsascoded/jupyterlite-demo).

I also replaced the README there, to explain a couple of deployment avenues, e.g.:
```bash
mkdir content && cp <some notebook>.ipynb content/
pip install jupyterlite jupyterlab
jupyter lite build --contents content --output-dir dist
# dist/ is now a full static Jupyterlite bundle including <some notebook>.ipynb
```

https://github.com/jupyterlite/demo/pull/47 is a draft PR with all that. I don't think it makes sense to merge as-is, but am mentioning since it seems relevant to the discussion here. It would be useful to have a simpler path to this info, starting from [jupyterlite/jupyterlite](https://github.com/jupyterlite/jupyterlite) or [the main demo page](https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html). Just finding the jupyterlite/demo repo took me a little bit of digging.

Perhaps I should turn that README into an example notebook in the demo repo, `how-to-host-your-own-jupyterlite.ipynb`, that just explains all this in one big Markdown cell?

**Comment by JacobJeppesen** [comment]
First of all, this project looks great! Being able to serve Jupyter Lab as a static page is awesome!

I've started making a minimal example of deploying it with Django, but it doesn't work. The repo is at 
https://github.com/JacobJeppesen/jupyterlite-django-deployment. I moved `index.html` to a `templates` folder, and changed the paths to match the path of the static files (see line 53 and 64 in https://github.com/JacobJeppesen/jupyterlite-django-deployment/blob/main/mysite/jupy/templates/index.html).

However, when I run it and go to the page, it seem like it hits some redirect issue, and the console just prints:
```
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 02, 2022 - 11:48:23
Django version 4.0.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[02/Apr/2022 11:48:27] "GET / HTTP/1.1" 200 2558
Not Found: /jupyter-lite.ipynb
Not Found: /jupyter-lite.json
Not Found: /index.html
[02/Apr/2022 11:48:27] "GET /jupyter-lite.json HTTP/1.1" 404 2289
[02/Apr/2022 11:48:27] "GET /jupyter-lite.ipynb HTTP/1.1" 404 2292
[02/Apr/2022 11:48:27] "GET /index.html HTTP/1.1" 404 2268
Not Found: /jupyter-lite.json
[02/Apr/2022 11:48:27] "GET /jupyter-lite.json HTTP/1.1" 404 2289
Not Found: /index.html
[02/Apr/2022 11:48:27] "GET /index.html HTTP/1.1" 404 2268
Not Found: /jupyter-lite.ipynb
[02/Apr/2022 11:48:27] "GET /jupyter-lite.ipynb HTTP/1.1" 404 2292
Not Found: /jupyter-lite.ipynb
Not Found: /jupyter-lite.json
Not Found: /index.html
[02/Apr/2022 11:48:27] "GET /jupyter-lite.ipynb HTTP/1.1" 404 2292
[02/Apr/2022 11:48:27] "GET /jupyter-lite.json HTTP/1.1" 404 2289
[02/Apr/2022 11:48:27] "GET /index.html HTTP/1.1" 404 2268
Not Found: /jupyter-lite.json
Not Found: /index.html
[02/Apr/2022 11:48:27] "GET /jupyter-lite.json HTTP/1.1" 404 2289
[02/Apr/2022 11:48:27] "GET /index.html HTTP/1.1" 404 2268
Not Found: /jupyter-lite.ipynb
``` 
... and it just continues to repeat this error until the browser gives up.

Do you know how to fix this? Am I missing a configuration somewhere?

**Comment by bollwyvl** [comment]
A lot of the bootstrap stuff is needed to be robust against very "dumb"
http servers without "standard" redirect tricks, and Django might be doing
something clever, e.g redirecting to /.

Looks like you need to ensure that it is serving, at least, the JSON and
html files... They tell the js app where everything is. The ipynb are
optional, but you probably want to serve them, too, for cleaner logs.

**Comment by JacobJeppesen** [comment]
I changed it such that Django acts as a "dumb" http server when serving JupyterLite, and serves the files directly from the collected static files (just had to install whitenoise to allow this). Everything seems to work now. Looking back, this is really how I should have done it to start with :smile:

**Comment by bollwyvl** [comment]
Great, glad that worked out.

If we can develop the use cases (on a separate issue/repo) it would very
well make sense to have a proper jupyterlite-django reusable app (in
another repo in this org) that depended on the core jupyterlite for assets,
and hoisted more of the configuration to the Django layer.

The collectstatic phase, which is pretty much the bane of my existence,
from a package management and deployment standpoint, would nonetheless be a
good match for how lite works.

**Comment by JacobJeppesen** [comment]
Sounds like a great idea. My use case is to use JupyterLite for "interactive" documentation. For websites already based on Django, it is very nice to be able to serve JupyterLab with some sample notebooks so easily.

**Comment by jtpio** [comment]
> If anyone else needs this, the working example is here: https://github.com/JacobJeppesen/jupyterlite-django-deployment

Nice thanks @JacobJeppesen!

Would you like to contribute the Django as a new how-to guide in the docs? https://jupyterlite.readthedocs.io/en/latest/howto/index.html#deploying

**Comment by jtpio** [comment]
Closing as the documentation now has a few guides for deploying on various platforms: https://jupyterlite.readthedocs.io/en/stable/howto/index.html#deploying

Please feel free to open new issues and/or PRs to add more deployment options, thanks!
