### ISSUE TITLE
Download binary file from the UI does not work

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite#676]
## Description

If you try downloading a file with type `base64` from the UI (right click + download) then it downloads a file with the content being the base64 string, which makes it broken.

## Reproduce

1. Upload an image in the UI
2. Download it back
3. Try to open it with your favorite image viewer, it doesn't work
4. Look at the file content, you'll see the base64 string instead of raw bytes

## Expected behavior

It should save bytes

**Comment by martinRenou** [comment]
Currently the content managing is implemented by routing all `/api/contents` requests to our own IContent logic. I wonder if overwriting the default drive instaed wouldn't fix this issue.

**Comment by vasiljevic** [comment]
> Currently the content managing is implemented by routing all `/api/contents` requests to our own IContent logic. I wonder if overwriting the default drive instaed wouldn't fix this issue.

Maybe it can be fixed easier. Looks like we can only modify functions [downloadContent](https://github.com/jupyterlite/jupyterlite/blob/34a19bbc89973a9faaf8155e40e827ab8b6ca190/packages/application-extension/src/index.tsx#L228) and  [formatContent](https://github.com/jupyterlite/jupyterlite/blob/34a19bbc89973a9faaf8155e40e827ab8b6ca190/packages/application-extension/src/index.tsx#L237) from [/packages/application-extension/src/index.tsx](https://github.com/jupyterlite/jupyterlite/blob/34a19bbc89973a9faaf8155e40e827ab8b6ca190/packages/application-extension/src/index.tsx) (lines 228-243) and additionaly modify code at two places in the same file where we call those two functions.

Since I am not familiar with the JupyterLite dev environmet, I may try to make a provisional pull request if you think this is appropriate.

**Comment by vasiljevic** [comment]
Look like pull request #775 works:

![image](https://user-images.githubusercontent.com/10418572/185566686-9486d122-d917-4bad-bd6d-5f67c02452fb.png)
