### ISSUE TITLE
Error message "Failed to load  :8000/api/contents/all.json:1"

### ISSUE THREAD

**Issue by philipp-strack** [jupyterlite/jupyterlite#770]
## Description

A fresh install of of jupyterlite from git gives the following error message:

Failed to load resource: the server responded with a status of 404 (File not found) :8000/api/contents/all.json:1 

## Reproduce

install jupyterlite from github
doit build
doit serve

## Expected behavior

I am not sure this is a problem at all, but a fresh installation of jupyterlite produces the above error and some similar errors.

**Comment by jtpio** [comment]
Thanks @philipp-strack for reporting.

This error indicates there is no indexed content. This is not a critical error and the main app should be able to continue working.

Since files are served statically, JupyterLite needs to look for a well-known file to retrieve the content at startup. If this file doesn't exist it gives a 404. Normally it will go away if you pass some contents at build time for example with the `--contents` CLI flag.

Maybe we could add some note to https://jupyterlite.readthedocs.io/en/latest/howto/content/files.html to mention this? Would you like to open a PR? Thanks!
