### ISSUE TITLE
BadZipFile Error when launching pyodide kernel via JuptyerLiteServer

### ISSUE THREAD

**Issue by stevejpurves** [jupyterlite/jupyterlite#864]
## Description
This issue is encountered when using the `JuptyerLiteServer` class within `thebe`.

The JupyterLiteServer appears to start successfully and begins initializing the kernel, but then an error occurs part way through initialization. This does not appear to be related to the wheels provided by JupyterLite, which appear to be loaded correctly -- instead it appears to be an issue with package loading inside the pyodide kernel? is this potentially a configuration issue when using the server within thebe?

The javascript console shows:

![image](https://user-images.githubusercontent.com/1473646/200330099-0ff870e4-6bd1-40ed-b3ec-6126b5b0f40e.png)

The network tab shows:

![image](https://user-images.githubusercontent.com/1473646/200330389-77d26370-c277-4ac7-ab0f-c5094ab1df04.png)

The only 404 in the network list is related to the service worker. This has not been configured as it was assumed this was optional and needed only to enable the jupyterlite file system extension?

## Reproduce

The issue is encountered in the development branch of thebe here: https://github.com/executablebooks/thebe/pull/569
It could be reproduced locally by:

1. checkout the branch
2. install 16, npm 8, turborepo
3. cd thebe
4. npm install
5. npm run build; npm run build:demo
7. cd apps/simple
8. npm run start:simple
9. Open a webrowser using the link shown in the console and go to the JupyterLite example
10. Click activate

## Expected behavior

Expecting the packages to load successfully

## Context

- JupyterLite version: 0.1.0-beta.14
- Operating System and version: any
- Browser and version: any

**Comment by stevejpurves** [comment]
is this error due to a failure of micropip to download a valid package for one of the dependencies it is trying to load? in which case this is not a JupyterLite issue at all?

**Comment by bollwyvl** [comment]
>  400: services

Do you explicitly disable the service worker for _reasons_... understandable, as it has a lot of pointy edges... but also unlocks some pretty key use cases for the main app.

The screenshots are firefox: would you perhaps be in private browsing mode? Have you tried other browsers? Can you determine the last `.whl` loaded that might be failing? Ideally with a server log rather than screenshots.

Do you have a public reproducer, e.g. binder, a deployed site, readthedocs, etc? For lite stuff, having per-PR-push RTD deploys has been absolutely critical.

**Comment by bollwyvl** [comment]
> have not loaded / setup the service worker

as a quick fix, you could roll back and _hard pin_ to a version that doesn't include the service worker/unified contents, then, e.g. `b9`. things are _not_ going to work the way one expects if it's half-deployed.

otherwise, you'd need to correctly wire up the service worker before debugging files-in-kernels: for product sites, you'd _absolutely_ want the serviceworker, if possible, as it provides a _substantial_ cache benefit, especially for pyodide.

> server log - are you referring to logs that might be produced by the JupyterLiteServer instance?

web server. what files actually get served. again, this would be easiest with a binder/readthedocs/CI log, basically anything other than having to debug your code locally.

**Comment by stevejpurves** [comment]
Turns out the error above was due to webpack misconfiguration(!) resulting in files with `.whl` extensions that actually only contained webpack export statements. Closing this as there is a separate issue open for adding the service worker https://github.com/executablebooks/thebe/issues/575
