### ISSUE TITLE
Strange behavior with autocomplete

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlite/jupyterlite#961]
## Description

Pressing `Tab` to autocomplete duplicates the beginning of the line. It doesn't seem to happen in JupyterLab.

https://user-images.githubusercontent.com/4711805/214622632-dc9ab394-15d9-4429-afcc-c31b9b498624.mp4

**Comment by tonyfast** [comment]
we talked about this issue in the jupyter triage meeting today. it seems like this is a bug in some `IPython` versions.

cc: @krassowski

**Comment by krassowski** [comment]
Thanks Tony. The upstream issue is https://github.com/ipython/ipython/issues/13935 and upgrading to latest IPython version should fix this. This only happens when jedi is disabled, and it is indeed disabled in juypterlite:

https://github.com/jupyterlite/jupyterlite/blob/7971e0aa67b65f9df204f9ab12b0e727b0e9e952/packages/pyolite-kernel/py/pyolite/pyolite/interpreter.py#L26

**Comment by krassowski** [comment]
I believe this can be closed if you can upgrade to newer IPython
