### ISSUE TITLE
GitHub page requests JupyterLite app installation on Chrome

### ISSUE THREAD

**Issue by tylere** [jupyterlite/jupyterlite#981]
### Problem

While following the [Deploy your first JupyterLite website on GitHub Pages](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html) tutorial, the GitHub Action successfully created a GitHub page. But upon opening the page (https://tylere.github.io/my-test-jupyterlite/lab/index.html), the Chrome browser presents an "Install app?" dialog (see screenshot below). It is not clear whether the installation request should be confirmed (i.e. click *Install*), and it is not clear what will happen during that installation.

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/92862/218333548-df6e851c-edcd-47a8-ae69-10154f13e334.png">

Environment:
- MacOS 13.2
- Chrome Version 110.0.5481.77

Additional notes:
- When opening the GitHub page in the Safari browser (Version 16.3 (18614.4.6.1.5)), no similar "Install App" is encountered.

### Suggested Improvement

In the [Accessing the JupyterLite website](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#accessing-the-jupyterlite-website) section of the [Deploy your first JupyterLite website on GitHub Pages](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html) tutorial, add a paragraph describing:
- why the "Install app?" prompt appears, and 
- what steps will occur if the user chooses to install the app.

**Comment by bollwyvl** [comment]
That's a specific browser (and version)'s way of telling the user that the site can be run offline, where the contents of the cache will be served even if offline. This can be tried, even without pressing that button, and then disconnecting from the internet, restarting the browser, and navigating to that URL.

Pressing the button is purely cosmetic: it might add a button to the desktop, the browser start page, or somewhere else.

When visiting the page again when not connected, anything already loaded by default (configuration, contents index, all the JS/CSS to run the site) will be immediately available. If a user starts a pre-loaded notebook, _that_ file (and anything else it loads, such as kernel packages) will be available. 

Anything _not_ downloaded at some point will not be available, as we don't yet have a mechanism to tell the browsers all of the files a site _could_ install. This means opening a notebook a user _hadn't_ yet seen will fail, as at startup only metadata about the file is loaded. The same goes for any kernel packages that file might expect to be able to install.

As to this not working on another browser: lots of things don't "work" on other browsers, sometimes by design.

**Comment by jtpio** [comment]
> In the [Accessing the JupyterLite website](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#accessing-the-jupyterlite-website) section of the [Deploy your first JupyterLite website on GitHub Pages](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html) tutorial, add a paragraph describing:

Or maybe this could be documented more in a different guide to keep the quickstart guide as simple as possible.
